/* deveria funcionar  */


while (naoTerminou || TRUE)
	while (naoTerminou || TRUE)
		begin
			/* 1 comando  */
			if ( ( n / m ) !=  n * n )
				if((m = 2*o) || (  n >= m/n))
					begin
						if ( ( n / m ) !=  n * n )  writeln("Sim"); else writeln("nao");
						writeln("Fim");
					endif
				else
					begin
						if((m = 2*o) || (  n >= m/n))
						writeln("Fim");
						readln(n);
				endelse
			/* 2 comando  */
			writeln("Ola' ",nome);
			/* 3 comando  */
			n<-n+1;
			/* 4 comando  */
			naoTerminou<-n<MAXITER;
        endwhile

		
