/* deveria funcionar  */

if ( ( n / m ) !=  n * n )
	if((m = 2*o) || (  n >= m/n))
		begin
			while (naoTerminou || TRUE) 
				begin 
					while (naoTerminou || TRUE) begin 
					  writeln("Ola' ",nome);
					  n<-n+1;
					  naoTerminou<-n<MAXITER;
					  while (naoTerminou || TRUE) 
						begin 
							while (naoTerminou || TRUE) 
								begin 
								  writeln("Ola' ",nome);
								  n<-n+1;
								  naoTerminou<-n<MAXITER;
								endwhile
						endwhile
				endwhile
			endwhile
		endif
	else
		begin
			if((m = 2*o) || (  n >= m/n))
			writeln("Fim");
			readln(n);
				
		endelse
		
		
