/* deveria funcionar  */


while (naoTerminou || TRUE) 
	while (naoTerminou || TRUE)
		begin 
			writeln("Ola' ",nome);
			n<-n+1;
			naoTerminou<-n<MAXITER;
			if ( ( n / m ) !=  n * n )
				if((m = 2*o) || (  n >= m/n))
					begin
						if ( ( n / m ) !=  n * n )  writeln("Sim"); else writeln("nao");
						writeln("Fim");
					endif
				else
					begin
						if((m = 2*o) || (  n >= m/n))
						writeln("Fim");
						readln(n);
				
				endelse

			
        endwhile
		
		
