/* deveria funcionar  */



if((m = 2*o) || (  n >= m/n))
	begin
		if ( ( n / m ) !=  n * n )  writeln("Sim"); else writeln("nao");
		writeln("Fim");
	endif
else
	begin
		if((m = 2*o) || (  n >= m/n))
			begin
				if ( ( n / m ) !=  n * n )  writeln("Sim"); else writeln("nao");
				writeln("Fim");
		    endif
		else
			begin
				if (verdadeiro)  writeln("Sim"); else writeln("nao");
				readln(n);
			endelse
	endelse