boolean naoTerminou <- FALSE;
int n <- 2, m <- 0, MAXITER<-25544;
string st <- "dddd";
final t <- "aaa";
final bla <- 150;
string nome;
boolean verdadeiro;

while (naoTerminou || TRUE)
	while (naoTerminou || TRUE)
		begin
			/* 1 comando  */
			if ( ( n / m ) !=  n * n )
				if((m = 2*0) || (  n >= m/n))
					begin
						if ( ( n / m * m + 5 - 9 ) !=  n * n )  writeln("Sim"); else writeln("nao");
						writeln("Fim");
					endif
				else
					begin
						if((m = 2*0) || (  n >= m/n))
						writeln("Fim");
						readln(n);
					endelse
			/* 2 comando  */
			writeln("Ola' ",nome);
			/* 3 comando  */
			n<-n+1;
			/* 4 comando  */
			naoTerminou<-n<MAXITER;
        endwhile
		

while (naoTerminou || TRUE) while (naoTerminou || TRUE)	begin   writeln("Ola' ",nome);  n<-n+1;  naoTerminou<-n<MAXITER;      endwhile

while (naoTerminou || TRUE) 
	begin 
		while (naoTerminou || TRUE) begin 
		  writeln("Ola' ",nome);
		  n<-n+1;
		  naoTerminou<-n<MAXITER;
		  while (naoTerminou || TRUE) 
			begin 
				while (naoTerminou || TRUE) 
					begin 
					  writeln("Ola' ",nome);
					  n<-n+1;
					  naoTerminou<-n<MAXITER;
					endwhile
			endwhile
	endwhile
endwhile

if((m = 2*0) || (  n >= m/n))
	begin
		if ( ( n / m ) !=  ((n * n) / m + 2) )  writeln("Sim"); else writeln("nao");
		writeln("Fim");
	endif
else
	begin
		if((m = 2*0) || (  n >= m/n))
			begin
				if ( (( n / m ) <=  n * n ) && (( n / m ) >=  n * n ) || ((- 8 + n / m + 9 *8 ) >  n * n ))  writeln("Sim"); else writeln("nao");
				writeln("Fim");
		    endif
		else
			begin
				if (verdadeiro)  writeln("Sim"); else writeln("nao");
				readln(n);
			endelse
	endelse